// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8EBVoNEIvKRy6r1FlYs4LPLUuMVI_af0',
    appId: '1:264553557631:web:99f544399178ba7b1f594a',
    messagingSenderId: '264553557631',
    projectId: 'whatsapp-clone-54cec',
    authDomain: 'whatsapp-clone-54cec.firebaseapp.com',
    storageBucket: 'whatsapp-clone-54cec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApD35RYBjG8TGdpG7Ba6jNBtCS7eFqcj0',
    appId: '1:264553557631:android:7ea96079e6bd18801f594a',
    messagingSenderId: '264553557631',
    projectId: 'whatsapp-clone-54cec',
    storageBucket: 'whatsapp-clone-54cec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRxFS6CPkwEos4ggGoho90DMLCUYzvLWg',
    appId: '1:264553557631:ios:4682133fdde39a311f594a',
    messagingSenderId: '264553557631',
    projectId: 'whatsapp-clone-54cec',
    storageBucket: 'whatsapp-clone-54cec.appspot.com',
    iosClientId: '264553557631-svdubg9acogvnfif3g4hmm7oo7rjk5v5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWhatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRxFS6CPkwEos4ggGoho90DMLCUYzvLWg',
    appId: '1:264553557631:ios:4682133fdde39a311f594a',
    messagingSenderId: '264553557631',
    projectId: 'whatsapp-clone-54cec',
    storageBucket: 'whatsapp-clone-54cec.appspot.com',
    iosClientId: '264553557631-svdubg9acogvnfif3g4hmm7oo7rjk5v5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWhatsappClone',
  );
}
